### ISSUE TITLE
Definición de Bases de Datos transaccionales

### ISSUE THREAD

**Issue by PaPablo** [LucianoFromTrelew/datawarehouse-patsur#1]
Se debe tener acceso a las 2 bases de datos operacionales de la organización

> Implementar la bd operacional de la cooperativa PatSur con sus dos sistemas de facturación

Las definiciones de tablas se encuentran en las filminas de teoría, por comidad se transcriben aquí:
* Sistema Facturación I (viejo):
   * Clientes (nro_Cliente, Nombre, tipo, dirección)
   * Producto (nro_Producto, Nombre, nro_categ, precio_actual)
   * Categoria (nro_categ, descripción)
   * Venta (Fecha_Vta, nro_Factura, nro_Cliente, Nombre, forma_pago)
   * Detalle_Venta(nro_factura, nro_producto, descripción, unidad, precio)

* Sistema de Facturación II (actual):
   * Clientes (cod_Cliente, Nombre, cod_tipo, dirección)
   * Tipo_Cliente (cod_tipo, descripción)
   * Producto (cod_Producto, Nombre, cod_categoria, cod_subcategoria, precio_actual)
   * Categoria (cod_categoria,  cod_subcategoría, descripción)
   * Venta (Fecha_Vta, Id_Factura, cod_Cliente, Nombre, cod_medio_pago)
   * Detalle_Venta(Id_factura, cod_producto, descripción, unidad, precio)
   * Medio_Pago( cod_Medio_Pago, descripción, valor, unidad, tipo_operación)
   * Tiempo ( Id_fecha, día, mes, trimestre, año)

**Comment by LuchoSerruya** [comment]
Resuelto en #7
