### ISSUE TITLE
Base de Datos DW

### ISSUE THREAD

**Issue by PaPablo** [LucianoFromTrelew/datawarehouse-patsur#2]
Del enunciado del TP:

> Implementar un DW (en otra BD u otro esquema de la misma BD en postgres) para la cooperativa PatSur, basado en la BD operacional creada y utilizando el esquema de Copo de Nieve presentado en la teoría (Tabla de hecho Ventas, medidas unidad y precio, dimensiones: sucursal, región, provincia, ciudad, cliente, tipo cliente, producto, categoría, subcategoría, y la dimensión Tiempo existente en todo DW).

**Comment by LuchoSerruya** [comment]
#10
