### ISSUE TITLE
Consultas para analistas

### ISSUE THREAD

**Issue by PaPablo** [LucianoFromTrelew/datawarehouse-patsur#4]
Se requieren las siguientes consultas para las vistas que los analistas requirieron

   * Venta vista por mes o por año, por sucursal, por región, por cliente y demás combinaciones entre las perspectivas.
   * El mínimo nivel de detalle que se quiere tener disponible para el análisis de las ventas ($ vendidos y unidades vendidas) es el de la facturas.
   * Es necesario conocer también de que manera influye, en las ventas de productos, la zona geográfica en la que están ubicados los locales.
   * De cada cliente se desea conocer cuales son los que generan mayores ingresos a la cooperativa.
   * Se necesitará hacer análisis diarios, mensuales, trimestrales y anuales.

**Comment by LuchoSerruya** [comment]
#19
