### ISSUE TITLE
Implementación en Herramienta Open Source a designar

### ISSUE THREAD

**Issue by PaPablo** [LucianoFromTrelew/datawarehouse-patsur#5]
Del enunciado:

> Se deberá hacer una implementación en una plataforma Open Source de Bussiness Intelligence, tomando los datos del Data Warehouse generado y armando un cubo con las medidas y dimensiones señaladas, luego utilizar la herramienta OLAP para generar las vistas indicadas (en #4)

[Artículo con suites para BI](https://opensource.com/business/16/6/top-business-intelligence-reporting-tools)

**Comment by LuchoSerruya** [comment]
#15

**Comment by PaPablo** [comment]
Si ya está hecho el merge, se cierra
