### ISSUE TITLE
Informe final

### ISSUE THREAD

**Issue by PaPablo** [LucianoFromTrelew/datawarehouse-patsur#6]
Consideraciones para el informe final

* Como hicieron los scripts de carga de la base de datos operacional y su llenado en general
* Como hicieron el script de carga del Data Warehouse para cada sistema de facturacion
* Las ejecuciones que hacen del script para llenar el DW
* Respuesta a las consultas del punto 4 (si no pueden hacer todas , algunas) con SQL con las extensiones de agrupamiento, etc
* El desarrollo de una pequeña reseña de la herramienta asignada de reporting o business intelligente y de como la pudieron implementar (o si no pudieron los problemas con los que se encontraron) y el o los reportes del punto 4 que pudieron implementar con dicha herramienta.

**Comment by LuchoSerruya** [comment]
#20
